#ifndef _ADTERR_H_
#define _ADTERR_H_
#include "diary.h"

/*Dairy Errors Code*/
typedef enum ADTErr {
    ERR_OK =0,
    ERR_GENERAL,
    ERR_MEETINGS_ARRAY_OVERFLOW,
    ERR_MEETINGS_ARRAY_UNDERFLOW,
    ERR_POINTER_NOT_INTIALIZED,
    ERR_REALLOCATION_FAILURE,
    ERR_MEETING_DOES_NOT_EXIST, 
    ERR_INVALID_MEETING_INPUTS, 
    ERR_ALLOCATION_FAILURE,
    ERR_MEETING_OVERLAP,
    ERR_OCCURED_WHILE_OPENING_THE_FILE
        
} ADTErr;




#endif /*_ADTERR_H_*/
