#include <math.h>
#include <stdlib.h> /*callloc*/ 
#include <stdio.h>
/**
 * class Point2D
{
public:
	Point2D();
	Point2D(double _x, double _y);

	double GetX() const;
	double GetY() const;
	double Distance(const Point2D& _other) const;

	Point2D &operator+=(const Point2D& _other);
	Point2D &operator*=(double _factor);

private:
	double m_x;
	double m_y;		
};
*/



typedef struct Point2D{
	double m_x;
	double m_y;	
	} Point2D;


/**
 * option one - build on heap
 * 
Point2D* Create_Point2D(void)
{
	return (Point2D*)calloc(1,sizeof(Point2D));
}
**/
/*option 2 - build on stack.
  */
void Create_Point2D(Point2D* const _this)
{
	_this->m_x = 0;
	_this->m_y = 0;
}

/** default copy ctor generated by compiler
 * */

void Create_Point2D_CopyCtor(Point2D* const _this, )






/**
Point2D(double _x, double _y);*/

void Create_Point2D_From_Point(Point2D* _this, double _x, double _y)
{
	_this->m_x = _x;
	_this->m_y = _y;
}




double _Point2D_Get_Mx(const Point2D* const _this)
{
	return _this->m_x;
}


double _Point2D_Get_My(const Point2D* const _this)
{
	return _this->m_y;
}

/**
double Point2D::Distance(const Point2D& _other) const
{
	double dx = m_x - _other.m_x;
	double dy = m_y - _other.m_y;
	return sqrt(dx * dx + dy * dy);
}**/

double _Calc_Distance(const Point2D* const _this , const Point2D* const _other)
{
	double dx = _this->m_x - _other->m_x;
	double dy = _this->m_y - _other->m_y;
	return sqrt(dx * dx + dy * dy);
}

/**
 * Point2D& Point2D::operator+=(const Point2D& _other)
{
	m_x += _other.m_x;
	m_y += _other.m_y;
	
	return *this;
}**/

Point2D* const _Add_Point2D_(Point2D* const _this, const Point2D* const _other)
{
	_this->m_x += _other->m_x;
	_this->m_y += _other->m_y;
	return _this;
}


/**
 * Point2D& Point2D::operator*=(double _factor)
{
	m_x *= _factor;
	m_y *= _factor;
	
	return *this;
}
 * 
 * */
Point2D* const _Mult_Point2D_(Point2D* const _this, double _factor)
{
	_this->m_x *= _factor;
	_this->m_y *= _factor;
	return _this;
}


/**
 * void pointless()
{
	Point2D p0;
	Point2D p1(0,10);
	printf("distance p0 --> p1 == %f\n", p0.Distance(p1));

	Point2D dxy(+4, -7);
	p1 += dxy;
	printf("%f, %f\n", p1._Point2D_Get_Mx(), p1._Point2D_Get_My());
	printf("now distance p0 --> p1 == %f\n", p0.Distance(p1));
}

 * **/


void MyPointless(void)
{
	Point2D P0,P1, dxy;
	
	Create_Point2D(&P0);
	
	
	Create_Point2D_From_Point(&P1, 0, 10);
	printf("distance p0 --> p1 == %f\n", _Calc_Distance(&P0 , &P1));
	
	
	Create_Point2D_From_Point(&dxy, 4, -7);
	
	_Add_Point2D_(&P1, &dxy);
	printf("%f, %f\n", P1.m_x, P1.m_y);
	printf("now distance p0 --> p1 == %f\n", _Calc_Distance(&P0 , &P1));
}

/**********************************************************************/
/**PHASE 2*/
/**********************************************************************/


/****
class NamedPoint2D : public Point2D
{
public:
	NamedPoint2D(const char *_name = "origin");
	NamedPoint2D(double _x, double _y, const char *_name = "anonymous Point");
	NamedPoint2D(const Point2D& point, const char *_name = "anonymous Point");
	const char *GetName() const;

private:
	const char *m_name;	
};


NamedPoint2D::NamedPoint2D(const char *_name)
: m_name(_name)
{
}

NamedPoint2D::NamedPoint2D(double _x, double _y, const char *_name)
: m_name(_name), Point2D(_x, _y)
{
}

NamedPoint2D::NamedPoint2D(const Point2D& _point, const char *_name)
: m_name(_name), Point2D(_point)
{
}

const char *NamedPoint2D::GetName() const
{
	return m_name;
}
**/

typedef struct NamedPoint2D {
	Point2D m_base;
	const char *m_name;	
	}NamedPoint2D;


void _Create_Named_Point2D_From_Const_CharPtr(NamedPoint2D* const this, const char* name)
{
	Create_Point2D(&this->m_base);
	(this->m_name) = name;
}

void _Create_Named_Point2D_From_Const_CharPtr_And_Point(NamedPoint2D* const this, const char* name, double _x, double _y)
{
	Create_Point2D_From_Point(&this->m_base, _x, _y);
	(this->m_name) = name;
}


void CreateNamedPoint2D__FromCurrentObject(Point2D* const point, NamedPoint2D* const this, const char* name)
{
	
	this->m_base.m_x = point->m_x ; /*copmiler generate/provide this code inline as default copy ctor*/
	this->m_base.m_y = point->m_y ; /*copmiler generate/provide this code inline as default copy ctor*/
	(this->m_name) = name;
}

const char* NamedPoint2D__GetName(const NamedPoint2D* const this)
{
	return this->m_name;
}


/**
 * class Rectangle
{
public:
	Rectangle(const Point2D& _a, const Point2D& _b, const char *_name = "anonymous Rectangle");

	const char *GetName() const;
	double CalcArea() const;

private:
	NamedPoint2D m_a;
	Point2D m_b;
	static const int s_curvature = 1;	
};



Rectangle::Rectangle(const Point2D& _a, const Point2D& _b, const char *_name)
: m_a(_a, _name), m_b(_b)
{
}

const char *Rectangle::GetName() const
{
	return m_a.GetName();
}

double Rectangle::CalcArea() const
{
	Point2D p1(m_a.GetX(), m_b.GetY());
	double sideA = m_a.Distance(p1);
	double sideB = m_a.Distance(Point2D(m_b.GetX(), m_a.GetY()));
	return sideA * sideB * s_curvature;
}

 * */

const int s_curvature =1;

typedef struct Rectangle{
	NamedPoint2D m_a;
	Point2D m_b;
	}Rectangle; 


void CreateRectangle(Point2D* const a_base, const Point2D* const b_base, Rectangle* this, const char *_name)
{
	Point2D temp;
	double x,y;
	CreateNamedPoint2D__FromCurrentObject(a_base, &this->m_a, _name);
	 /*Point2D* const temp = (Point2D*)calloc(1,sizeof(Point2D)) ;*/
	 
	 
	 
	 x = _Point2D_Get_Mx(b_base);
	 y = _Point2D_Get_My(b_base);
	 Create_Point2D_From_Point(&temp, x,y);
	/**
	double xx =  _Point2D_Get_Mx(&temp);
	double yy =  _Point2D_Get_My(&temp);
	 
	 
	 this->m_b->m_x = temp.m_x;
	 this->m_b->m_y = temp.m_y; **/
	 this->m_b = temp;
	 
}


const char* RectangleGetName(const Rectangle* const this)
{
	return this->m_a.m_name;
}

double RectangleCalcArea(const Rectangle* const this)
{
	Point2D temp;
	Point2D newtemp;
	double x,y,sideA,sideB;
	x = _Point2D_Get_Mx(&this->m_a.m_base); 
	y = _Point2D_Get_My(&this->m_a.m_base);
	Create_Point2D_From_Point(&temp, x, y);
	sideA = _Calc_Distance(&this->m_a.m_base, &temp);
	
	
	
	Create_Point2D_From_Point(&newtemp, _Point2D_Get_My(&this->m_b), _Point2D_Get_My(&this->m_b));
	sideB = _Calc_Distance(&this->m_a.m_base, &newtemp);
	return sideA * sideB * s_curvature;
	
}


/**
 * double _Calc_Distance(const Point2D* const _this , const Point2D* const _other)
{
	double dx = _this->m_x - _other->m_x;
	double dy = _this->m_y - _other->m_y;
	return sqrt(dx * dx + dy * dy);
}
* 
* 
* 
* 
* 
* void dog()
{
	NamedPoint2D home(5,7, "home");
	Point2D point(home);
	NamedPoint2D dog(point);

	dog *= 2;
	printf("Distance from %s to %s is %f\n", home.GetName(), dog.GetName(), home.Distance(dog));
}
* 
* 
* */

/*
void dog()
{
	NamedPoint2D home, dog;
	Point2D point;
	 
	_Create_Named_Point2D_From_Const_CharPtr_And_Point(&home, "home", 5, 7);
	
	
	
	Point2D point(home);
	NamedPoint2D dog(point);

	dog *= 2;
	printf("Distance from %s to %s is %f\n", home.GetName(), dog.GetName(), home.Distance(dog));
}

void area()
{
	Point2D p0;
	Point2D p1(12,12);
	Rectangle r(p0, p1);
	
	printf("The area of %s is %f\n", r.GetName(), r.CalcArea());
	printf("rectangle size %zu", sizeof(r));
}
*/





int main()
{
	
	/**MyPointless();
	*/
	return 0;
}







