#ifndef _ADTDEFS_H_
#define _ADTDEFS_H_

typedef enum
{
	/* General ADT Errors */
	ERR_OK                            =0,
	ERR_GENERAL,
	ERR_NOT_INITIALIZED,
	ERR_ALLOCATION_FAILED,
	ERR_REALLOCATION_FAILED,
	ERR_UNDERFLOW,
	ERR_OVERFLOW,
	ERR_NODE_OVERLAP,
	ERR_WRONG_INDEX,
	ERR_DATA_EXIST,
	ERR_DATA_DOES_NOT_EXIST,
	ERR_INVALID_DATA,
	/*stack errors*/
	ERR_STACK_OK                            =10,
	ERR_STACK_OVERFLOW,
	ERR_STACK_UNDERFLOW,
	ERR_STACK_NOT_INITIALIZED,
	ERR_STACK_ALLOCATION_FAILED,
	ERR_STACK_REALLOCATION_FAILED,
	ERR_STACK_GENERAL,
	ERR_EMPTY_STACK
} ADTErr;



#endif /*_ADTDEFS_H_*/
